// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIETE.Data;

#nullable disable

namespace SIETE.Migrations
{
    [DbContext(typeof(SIETEContext))]
    partial class SIETEContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIETE.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAccountablePerson")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("OfficeID")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PositionID")
                        .HasColumnType("int");

                    b.Property<string>("Suffix")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("OfficeID");

                    b.HasIndex("PositionID");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            EmailAddress = "niere@gmail.com",
                            FirstName = "Ernest",
                            IsAccountablePerson = true,
                            IsActive = true,
                            LastName = "Niere",
                            OfficeID = 1,
                            PhoneNumber = "09123456789",
                            PositionID = 1,
                            Suffix = "Jr.",
                            Title = "Mr."
                        });
                });

            modelBuilder.Entity("SIETE.Models.FundCluster", b =>
                {
                    b.Property<int>("FundClusterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FundClusterID"));

                    b.Property<string>("FundClusterCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FundClusterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FundClusterID");

                    b.ToTable("FundCluster");

                    b.HasData(
                        new
                        {
                            FundClusterID = 1,
                            FundClusterCode = "F101",
                            FundClusterName = "MDS"
                        },
                        new
                        {
                            FundClusterID = 2,
                            FundClusterCode = "F102",
                            FundClusterName = "TRUST RECEIPTS"
                        },
                        new
                        {
                            FundClusterID = 3,
                            FundClusterCode = "F103",
                            FundClusterName = "TRUST TRAINING"
                        },
                        new
                        {
                            FundClusterID = 4,
                            FundClusterCode = "F104",
                            FundClusterName = "CFAG"
                        });
                });

            modelBuilder.Entity("SIETE.Models.Office", b =>
                {
                    b.Property<int>("OfficeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficeID"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parent_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RespCenter_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfficeID");

                    b.ToTable("Office");

                    b.HasData(
                        new
                        {
                            OfficeID = 1,
                            Acronym = "Ad",
                            IsActive = true,
                            OfficeName = "Admin Office",
                            OfficeType = "Office",
                            Parent_Code = "Admin",
                            RespCenter_Code = "Admin"
                        });
                });

            modelBuilder.Entity("SIETE.Models.PlantillaPosition", b =>
                {
                    b.Property<int>("PositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PositionID");

                    b.ToTable("PlantillaPosition");

                    b.HasData(
                        new
                        {
                            PositionID = 1,
                            IsActive = true,
                            PositionTitle = "Programmer"
                        });
                });

            modelBuilder.Entity("SIETE.Models.PriceThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PropertyThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SPThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PriceThreshold");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EffectiveDate = new DateTime(2025, 5, 14, 16, 33, 40, 752, DateTimeKind.Local).AddTicks(7940),
                            PropertyThreshold = 50000m,
                            SPThreshold = 15000m
                        });
                });

            modelBuilder.Entity("SIETE.Models.Property.Property", b =>
                {
                    b.Property<int>("PropertyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateAcquired")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FundClusterID")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyCardID")
                        .HasColumnType("int");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StockPropNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitMeasurement")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PropertyID");

                    b.HasIndex("FundClusterID");

                    b.HasIndex("PropertyCardID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("SIETE.Models.Property.PropertyAssignment", b =>
                {
                    b.Property<int>("PropertyAssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyAssignmentID"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PropertyID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("PropertyAssignmentID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("PropertyID");

                    b.ToTable("PropertyAssignment");
                });

            modelBuilder.Entity("SIETE.Models.Property.PropertyAssignmentHistory", b =>
                {
                    b.Property<int>("HistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryID"));

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LatestQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PreviousQuantity")
                        .HasColumnType("int");

                    b.Property<int>("PropertyID")
                        .HasColumnType("int");

                    b.Property<int?>("PropertyTransactionID")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TPSNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransferType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HistoryID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("PropertyID");

                    b.HasIndex("PropertyTransactionID");

                    b.ToTable("PropertyAssignmentHistory");
                });

            modelBuilder.Entity("SIETE.Models.Property.PropertyCard", b =>
                {
                    b.Property<int>("PropertyCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyCardID"));

                    b.Property<int>("CurrentStockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("PropertyCardName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PropertyDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PropertyUnitMeasurement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PropertyCardID");

                    b.ToTable("PropertyCard");
                });

            modelBuilder.Entity("SIETE.Models.Property.PropertyTransaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("TransactionID");

                    b.ToTable("PropertyTransaction");
                });

            modelBuilder.Entity("SIETE.Models.Property.PropertyTransactionDetail", b =>
                {
                    b.Property<int>("PropertyTransactionDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyTransactionDetailID"));

                    b.Property<int?>("AssignmentID")
                        .HasColumnType("int");

                    b.Property<string>("DisposalType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PropertyID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PropertyTransactionDetailID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("PropertyID");

                    b.HasIndex("TransactionID");

                    b.ToTable("PropertyTransactionDetail");
                });

            modelBuilder.Entity("SIETE.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsVatRegistered")
                        .HasColumnType("bit");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TIN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SupplierID");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("SIETE.Models.Supply.StockCard", b =>
                {
                    b.Property<int>("StockCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockCardID"));

                    b.Property<int>("CurrentStockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("StockCardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StockDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("StockUnitMeasurement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StockCardID");

                    b.ToTable("StockCard");
                });

            modelBuilder.Entity("SIETE.Models.Supply.Supply", b =>
                {
                    b.Property<int>("SupplyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplyID"));

                    b.Property<DateTime>("DateAcquired")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FundClusterID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StockCardID")
                        .HasColumnType("int");

                    b.Property<string>("StockPropNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("SupplierID")
                        .HasColumnType("int");

                    b.Property<string>("SupplyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitMeasurement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplyID");

                    b.HasIndex("FundClusterID");

                    b.HasIndex("StockCardID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Supply");
                });

            modelBuilder.Entity("SIETE.Models.Supply.SupplyInDetail", b =>
                {
                    b.Property<int>("DetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailID"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SupplyID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DetailID");

                    b.HasIndex("SupplyID");

                    b.HasIndex("TransactionID");

                    b.ToTable("SupplyInDetail");
                });

            modelBuilder.Entity("SIETE.Models.Supply.SupplyOutDetail", b =>
                {
                    b.Property<int>("DetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailID"));

                    b.Property<int>("OfficeID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SupplyID")
                        .HasColumnType("int");

                    b.Property<int>("TransactionID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DetailID");

                    b.HasIndex("OfficeID");

                    b.HasIndex("SupplyID");

                    b.HasIndex("TransactionID");

                    b.ToTable("SupplyOutDetail");
                });

            modelBuilder.Entity("SIETE.Models.Supply.SupplyTransaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("TransactionID");

                    b.ToTable("SupplyTransaction");
                });

            modelBuilder.Entity("SIETE.Models.UserAccount", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("UserAccount");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            EmployeeID = 1,
                            Password = "Admin123",
                            Role = 1,
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("SIETE.Models.Employee", b =>
                {
                    b.HasOne("SIETE.Models.Office", "Office")
                        .WithMany("Employees")
                        .HasForeignKey("OfficeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SIETE.Models.PlantillaPosition", "PlantillaPosition")
                        .WithMany("Employees")
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Office");

                    b.Navigation("PlantillaPosition");
                });

            modelBuilder.Entity("SIETE.Models.Property.Property", b =>
                {
                    b.HasOne("SIETE.Models.FundCluster", "FundCluster")
                        .WithMany()
                        .HasForeignKey("FundClusterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIETE.Models.Property.PropertyCard", "PropertyCard")
                        .WithMany("Properties")
                        .HasForeignKey("PropertyCardID");

                    b.HasOne("SIETE.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FundCluster");

                    b.Navigation("PropertyCard");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SIETE.Models.Property.PropertyAssignment", b =>
                {
                    b.HasOne("SIETE.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIETE.Models.Property.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("SIETE.Models.Property.PropertyAssignmentHistory", b =>
                {
                    b.HasOne("SIETE.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID");

                    b.HasOne("SIETE.Models.Property.Property", "Property")
                        .WithMany("PropertyAssignmentHistory")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIETE.Models.Property.PropertyTransaction", "PropertyTransaction")
                        .WithMany()
                        .HasForeignKey("PropertyTransactionID");

                    b.Navigation("Employee");

                    b.Navigation("Property");

                    b.Navigation("PropertyTransaction");
                });

            modelBuilder.Entity("SIETE.Models.Property.PropertyTransactionDetail", b =>
                {
                    b.HasOne("SIETE.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID");

                    b.HasOne("SIETE.Models.Property.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIETE.Models.Property.PropertyTransaction", "PropertyTransaction")
                        .WithMany("PropertyTransactionDetails")
                        .HasForeignKey("TransactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Property");

                    b.Navigation("PropertyTransaction");
                });

            modelBuilder.Entity("SIETE.Models.Supply.Supply", b =>
                {
                    b.HasOne("SIETE.Models.FundCluster", "FundCluster")
                        .WithMany()
                        .HasForeignKey("FundClusterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIETE.Models.Supply.StockCard", "StockCard")
                        .WithMany("Supplies")
                        .HasForeignKey("StockCardID");

                    b.HasOne("SIETE.Models.Supplier", "Supplier")
                        .WithMany("Supplies")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FundCluster");

                    b.Navigation("StockCard");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SIETE.Models.Supply.SupplyInDetail", b =>
                {
                    b.HasOne("SIETE.Models.Supply.Supply", "Supply")
                        .WithMany()
                        .HasForeignKey("SupplyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIETE.Models.Supply.SupplyTransaction", "SupplyTransaction")
                        .WithMany("SupplyInDetails")
                        .HasForeignKey("TransactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supply");

                    b.Navigation("SupplyTransaction");
                });

            modelBuilder.Entity("SIETE.Models.Supply.SupplyOutDetail", b =>
                {
                    b.HasOne("SIETE.Models.Office", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIETE.Models.Supply.Supply", "Supply")
                        .WithMany()
                        .HasForeignKey("SupplyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIETE.Models.Supply.SupplyTransaction", "SupplyTransaction")
                        .WithMany("SupplyOutDetails")
                        .HasForeignKey("TransactionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");

                    b.Navigation("Supply");

                    b.Navigation("SupplyTransaction");
                });

            modelBuilder.Entity("SIETE.Models.UserAccount", b =>
                {
                    b.HasOne("SIETE.Models.Employee", "Employee")
                        .WithMany("UserAccounts")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SIETE.Models.Employee", b =>
                {
                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("SIETE.Models.Office", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SIETE.Models.PlantillaPosition", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SIETE.Models.Property.Property", b =>
                {
                    b.Navigation("PropertyAssignmentHistory");
                });

            modelBuilder.Entity("SIETE.Models.Property.PropertyCard", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("SIETE.Models.Property.PropertyTransaction", b =>
                {
                    b.Navigation("PropertyTransactionDetails");
                });

            modelBuilder.Entity("SIETE.Models.Supplier", b =>
                {
                    b.Navigation("Supplies");
                });

            modelBuilder.Entity("SIETE.Models.Supply.StockCard", b =>
                {
                    b.Navigation("Supplies");
                });

            modelBuilder.Entity("SIETE.Models.Supply.SupplyTransaction", b =>
                {
                    b.Navigation("SupplyInDetails");

                    b.Navigation("SupplyOutDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
